## Problem Statement

Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def Division_with_zero():
    return 5/0

try:
    Division_with_zero()
    
except ZeroDivisionError as zero:
    print("Taken care of dividing a number by 'ZERO' using Try and Except")

Taken care of dividing a number by 'ZERO' using Try and Except


Q.2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

    Output should come as below:
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [2]:
subjects=["Americans", "Indians"]
verbs=["Play", "watch"]
objects=["Baseball","Cricket"]

''' Method-1: Using nested for loop on each list for sentence formation '''

print('\n "Method-1 Output:" ')

for sub in subjects:
    for vrb in verbs:
        for obj in objects:
            sentences_list = [(sub + " " + vrb + " " + obj + ".")]
            print(*sentences_list)

''' Method-2: Using list comprehension instead of looping on each list for sentence formation'''            
print('\n "Method-2 Output:" ')

sentences_list = [(sub+" "+ vrb + " " + obj + ".") for sub in subjects for vrb in verbs for obj in objects]
for sentence in sentences_list:
    print(sentence)


 "Method-1 Output:" 
Americans Play Baseball.
Americans Play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians Play Baseball.
Indians Play Cricket.
Indians watch Baseball.
Indians watch Cricket.

 "Method-2 Output:" 
Americans Play Baseball.
Americans Play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians Play Baseball.
Indians Play Cricket.
Indians watch Baseball.
Indians watch Cricket.


Q.3 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [5]:
import numpy as np

'''To generate Alexandre Theophile Vandermonde Matrix, Need to iterate over each number in the input vector n times, 
n being the number of columns in the o/p matrix and output an intermediate vector. Use diff order formula based on 
increasing and decreasing condition.'''
   
def generate_vandermonde_matrix(input_vector, N, increasing=False):
    
    if not increasing:
        output_matrix = np.array([x**(N-1-i) for x in input_vector for i in range(N)]).reshape(input_vector.size,N)
        
    elif increasing:
         output_matrix = np.array([x**i for x in input_vector for i in range(N)]).reshape(input_vector.size,N)
    
    return output_matrix


input_vector = np.array([1,2,3,4,5])
no_of_col = 4
output_matrix_dec_order = generate_vandermonde_matrix(input_vector,no_of_col,False)
output_matrix_inc_order = generate_vandermonde_matrix(input_vector,no_of_col,True)

print("The input array is:",input_vector,"\n")
print("Number of columns in output matrix restricted / used to be:",no_of_col,"\n")
print("Alexandre Theophile Vandermonde matrix of the input array in decreasing order of powers:\n\n",output_matrix_dec_order,"\n")
print("Alexandre Theophile Vandermonde matrix of the input array in increasing order of powers:\n\n",output_matrix_inc_order,"\n \n")

input_vector = np.array([1,2,3,4,5,6,7])
no_of_col = 6
output_matrix_dec_order = generate_vandermonde_matrix(input_vector,no_of_col,False)
output_matrix_inc_order = generate_vandermonde_matrix(input_vector,no_of_col,True)

print("---------------------------------------------------------------\n \n")
print("The input array is:",input_vector,"\n")
print("Number of columns in output matrix restricted / used be:",no_of_col,"\n")
print("Alexandre Theophile Vandermonde matrix of the input array in decreasing order of powers:\n\n",output_matrix_dec_order,"\n")
print("Alexandre Theophile Vandermonde matrix of the input array in increasing order of powers:\n\n",output_matrix_inc_order,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix restricted / used to be: 4 

Alexandre Theophile Vandermonde matrix of the input array in decreasing order of powers:

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]] 

Alexandre Theophile Vandermonde matrix of the input array in increasing order of powers:

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]] 
 

---------------------------------------------------------------
 

The input array is: [1 2 3 4 5 6 7] 

Number of columns in output matrix restricted / used be: 6 

Alexandre Theophile Vandermonde matrix of the input array in decreasing order of powers:

 [[    1     1     1     1     1     1]
 [   32    16     8     4     2     1]
 [  243    81    27     9     3     1]
 [ 1024   256    64    16     4     1]
 [ 3125   625   125    25     5     1]
 [ 7776  1296   216    36     6     1]
 [16807  2401   343    49     7